# Generated by Django 3.1 on 2022-01-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendNewEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('chennai', 'Chennai'), ('banglore', 'Banglore'), ('kolkata', 'Kolkata')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SentEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('chennai', 'Chennai'), ('banglore', 'Banglore'), ('kolkata', 'Kolkata')], max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
