# Generated by Django 3.1 on 2022-01-14 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailAutomation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('chennai', 'Chennai'), ('banglore', 'Banglore'), ('kolkata', 'Kolkata')], max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='SentEmails',
        ),
    ]
